language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
install:
  - composer install --no-interaction
script:
  - if [[ $(phpenv version-name) != "7.0" ]]; then composer require --dev cweagans/composer-patches; fi
  - if [[ $(phpenv version-name) != "7.0" ]]; then rm -rf vendor/phpunit; fi
  - if [[ $(phpenv version-name) != "7.0" ]]; then composer install; fi
  - composer test
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
